PortfolioProject/Controllers/AboutController.cs
using Business.Concrete;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace PortfolioProject.Controllers
{
    public class AboutController : Controller
    {
        AboutManager aboutManager = new AboutManager(new EfAboutDal());
        [HttpGet]
        public IActionResult Index()
        {
            var editSkill = aboutManager.GetById(1).Data;
            return View(editSkill);
        }


        [HttpPost]
        public IActionResult Index(About about)
        {
            aboutManager.Update(about);
            return RedirectToAction("Index", "Default");
        }
    }
}

PortfolioProject/Views/About/Index.cshtml
@model Entities.Concrete.About
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
@using (Html.BeginForm("Index", "About", FormMethod.Post))
{

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Hakkımda Düzenleme Paneli</p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Id</label>
                        @Html.TextBoxFor(x=>x.AboutID,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x=>x.Title,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Yaş</label>
                        @Html.TextBoxFor(x=>x.Age,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Mail</label>
                        @Html.TextBoxFor(x=>x.Mail,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Telefon</label>
                        @Html.TextBoxFor(x=>x.Phone,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Adres</label>
                        @Html.TextBoxFor(x=>x.Address,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Görsel URL</label>
                        @Html.TextBoxFor(x=>x.ImageUrl,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Açıklama</label>
                        @Html.TextAreaFor(x=>x.Description,6,3,new{@class="form-control"})
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}