PortfolioProject/Controllers/SkillController.cs
 using Business.Concrete;
using Core.Utilities.Results;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace PortfolioProject.Controllers
{
    public class SkillController : Controller
    {
        SkillManager skillManager= new SkillManager(new EfSkillDal());
        public IActionResult Index()
        {
            var listedSkill = skillManager.GetAll().Data;
            return View(listedSkill);
        }
        [HttpGet]
        public IActionResult AddSkill()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.Add(skill);
            return RedirectToAction("Index");
        }
       
        public IActionResult DeleteSkill(int id)
        {
            var result = skillManager.GetById(id);
            var skill = result.Data;
            skillManager.Delete(skill.SkillID);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            var editSkill=skillManager.GetById(id).Data;
            return View(editSkill);
        }

        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
            skillManager.Update(skill);
            return RedirectToAction("Index");
        }
        
    }
}

PortfolioProject/Views/Skill/AddSkill.cshtml
@model Entities.Concrete.Skill
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
@using (Html.BeginForm("AddSkill", "Skill", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Yeni Yetenek Ekleme Paneli</p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x=>x.Title,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Değer</label>
                        @Html.TextBoxFor(x=>x.Value,new{@class="form-control"})
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>

}

PortfolioProject/Views/Skill/EditSkill.cshtml
@model Entities.Concrete.Skill
@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
@using (Html.BeginForm("AddSkill", "Skill", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description"> Yetenek Düzenleme Paneli</p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x=>x.SkillID,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x=>x.Title,new{@class="form-control"})
                    </div>
                    <div class="form-group">
                        <label>Değer</label>
                        @Html.TextBoxFor(x=>x.Value,new{@class="form-control"})
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>

}

PortfolioProject/Views/Skill/Index.cshtml
@using Entities.Concrete
@model List<Skill>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Listesi Tablosu</h3>
</div>
<!-- Light table -->
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Başlık</th>
                <th scope="col" class="sort" data-sort="status">Oran</th>
                <th scope="col">Sil</th>
                <th scope="col" class="sort" data-sort="completion">Düzenle</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="list">
            @foreach(var item in Model)
            {
                <tr>
                    <th>
                       @item.SkillID
                    </th>
                    <td class="budget">
                        @item.Title
                    </td>
                    <td>
                        <div class="d-flex align-items-center">
                            <span class="completion mr-2">@item.Value%</span>
                            <div>
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;"></div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td><a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-outline-danger">Sil</a></td>
                    <td><a href="/Skill/EditSkill/@item.SkillID" class="btn btn-outline-success">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    <a href="/Skill/AddSkill/" class="btn btn-outline-primary" >Yeni Yetenek Ekle</a>
</div>